### ISSUE TITLE
Wrong path for ip2location database

### ISSUE THREAD

**Issue by uso5** [ip2location/ip2location-cakephp#2]
Hi, 

In [IP2LocationCoresController.php on line 22 ](https://github.com/ip2location/ip2location-cakephp/blob/master/src/Controller/IP2LocationCoresController.php#L22) there is a invalid path to database. 

Currently the path is `...'src' . DS . 'data'...` but is should point to `...'src' . DS . 'Data'...`. Its not working on case sensitive OS.

Thanks

**Comment by ip2location-com** [comment]
Hi @uso5 

We have fixed the error.

Thank you.
