### ISSUE TITLE
IPv6 + IPv4 not working

### ISSUE THREAD

**Issue by yrat** [ip2location/ip2location-cakephp#3]
> Use the IPv4 BIN file if you just need to query IPv4 addresses.
> 
> Use the IPv6 BIN file if you need to query BOTH IPv4 and IPv6 addresses.

But when using the IPv6 BIN file, getting `countryCode => 'Invalid IPv6 address.' ` when  `$record = $this->IP2Location->get($this->request->clientIp());` with an IPv4 on `get()`

**Comment by yrat** [comment]
Using CakePHP2 and IP2Location v6.0

IPv4s work again when replacing `if($this->db['ip_version'] == self::IPV4)` by `if (!filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6))`

But IPv6s don't work in all cases, return `null`, so probably the new BINs are not compatible with that old IP2Location v6.0 on CakePHP2

**Comment by ip2location-com** [comment]
It is working fine based on our testing on the IP2Location v8 with CakePHP4.

Can you please try it again?
